### ISSUE TITLE
Problems setting up extramuros - not sure if its a tidal problem...

### ISSUE THREAD

**Issue by franticspider** [dktr0/extramuros#5]
Hello, I'm still trying to get extramuros working, but I'm not sure I've got it linking up to tidal properly. I'm running ubuntu 14.10. I think everything is installed correctly as I can use tidal via emacs. and the extramuros server appears to be working. 

I start the server using 

```
cd ~/extramuros
node server.js --password wibble
```

Then I start the client:

```
node client.js --server 127.0.0.1 --tidal --feedback --osc-port 8000 --password wibble
```

I open the browser window and enter the password, then try some tidal code in the first window:

```
d1 $ interlace (sound  "bd sn kurt") (every 3 rev $ sound  "bd sn:2")
```

This gives me the following error in the notification window: 

```
<interactive>:2:1: Not in scope: `d1'

<interactive>:2:6:
    Not in scope: `interlace'
    Perhaps you meant `interact' (imported from Prelude)

<interactive>:2:17:
    Not in scope: `sound'
    Perhaps you meant `round' (imported from Prelude)

<interactive>:2:39: Not in scope: `every'

<interactive>:2:47:
    Not in scope: `rev'
    Perhaps you meant `rem' (imported from Prelude)

<interactive>:2:53:
    Not in scope: `sound'
    Perhaps you meant `round' (imported from Prelude)
Prelude> Prelude> 
```

..which looks to me like a tidal problem. I've also tried this by starting dirt before the above but I get the same error. 

I'd be grateful if you could tell me what you think the problem might be. I'm thinking that the client isn't hooking up to tidal properly, but I don't know how to fix it

thanks,

Simon

**Comment by d0kt0r0** [comment]
Hi Simon,


At a quick glance, it looks like Tidal is not installed or available somehow.


What happens when you try this at the console (and then ghci console) - in a directory _other_ than ~/extramuros (to avoid the .ghci file there)?


cd /not/extramuros/directory
ghci -XOverloadedStrings
:m Sound.Tidal.Context
d1 <- dirtStream
d1 $ sound “bd cp”


Yours truly,
David


PS - a better place for this would be the extramuros discussion list on
lurk.org!



On Sep 10, 2015, at 7:16 AM, Simon Hickinbotham <notifications@github.com> wrote:


Hello, I'm still trying to get extramuros working, but I'm not sure I've got it linking up to tidal properly. I'm running ubuntu 14.10. I think everything is installed correctly as I can use tidal via emacs. and the extramuros server appears to
 be working. 
I start the server using 
cd ~/extramuros
node server.js --password wibble

Then I start the client:
node client.js --server 127.0.0.1 --tidal --feedback --osc-port 8000 --password wibble

I open the browser window and enter the password, then try some tidal code in the first window:
d1 $ interlace (sound  "bd sn kurt") (every 3 rev $ sound  "bd sn:2")

This gives me the following error in the notification window: 
<interactive>:2:1: Not in scope: `d1'

<interactive>:2:6:
    Not in scope: `interlace'
    Perhaps you meant `interact' (imported from Prelude)

<interactive>:2:17:
    Not in scope: `sound'
    Perhaps you meant `round' (imported from Prelude)

<interactive>:2:39: Not in scope: `every'

<interactive>:2:47:
    Not in scope: `rev'
    Perhaps you meant `rem' (imported from Prelude)

<interactive>:2:53:
    Not in scope: `sound'
    Perhaps you meant `round' (imported from Prelude)
Prelude> Prelude> 

..which looks to me like a tidal problem. I've also tried this by starting dirt before the above but I get the same error.

I'd be grateful if you could tell me what you think the problem might be. I'm thinking that the client isn't hooking up to tidal properly, but I don't know how to fix it
thanks,
Simon
—
Reply to this email directly or 
view it on GitHub.

**Comment by franticspider** [comment]
Hi David,

that worked like a charm! But I had to start dirt first like this:

cd ~/tidal/dirt/
./dirt &

then by following your instructions all worked fine.

d'you want me to move this conversation to lurk.org?

Simon

**Comment by d0kt0r0** [comment]
P {margin-top:0;margin-bottom:0;}


Hi Simon,

Hmmm... that suggests you do indeed have a working Tidal setup, so a bit more mysterious.

In the extramuros folder there is a file called .ghci which is an initializer for GHCI through which you access Tidal. If, somehow, that file is not being run when GHCI starts, there'd be no access to Tidal and you'd get errors like what you see there. I'm
 not sure why that file would not be run though.

You could confirm that it is there by doing a complete directory listening in the extramuros folder:
cd ~/extramuros
ls -a
(and then looking for the presence of .ghci in the list)

Probably it's there though (I can't imagine why it wouldn't be if you've recently cloned the github repository)...

Do you get any other error messages before the ones you quoted?  Also, what operating system are you using?

And yes, if you move this to the extramuros discussion list there would be some more eyes on the problem!

Yours truly,
David

**Comment by franticspider** [comment]
it's fixed! There was a permssions problem - group access to git/extramuros
and git/extramuros/.ghci  meant that ghci was ignoring the .ghci file. so

chmod g-w .ghci

and

chmod g-w ../extramuros

did the trick. (I don't know why ghci is so fussy about this...or how to
disable it..)

many thanks for your help with this David.

Simon

**Comment by d0kt0r0** [comment]
P {margin-top:0;margin-bottom:0;}


Ah, good to know!  Hopefully we'll see you on the extramuros list before too long anyway - though!


Yours truly,
David
